### ISSUE TITLE
Attach more than one file to Homework online submission

### ISSUE THREAD

**Issue by vitovt** [GibbonEdu/core#1023]
**Describe the bug**
When student submit online homework there is option to attach only one file.
![image](https://user-images.githubusercontent.com/315178/80320201-a6ace800-881d-11ea-806e-7555aafa8f72.png)

**To Reproduce**

1. Go to 'Home > Planner > Planner for **** > View Lesson Plan'
2. Scroll down to 'TEACHER RECORDED HOMEWORK'
3. Click on 'Type: File'
4. There is an option to add ONLY ONE file.

**Expected behavior**
* Would be great if student can add multiple files\
* Even better if student have input HTML editor form like "STUDENT RECORDED HOMEWORK" to answer the teachers qustion and ability to add multiple files.

**Your System**
 - Gibbon version [e.g. v19.0.00] vanilla
 - Browser [chrome]

**Comment by SKuipers** [comment]
Hi @vitovt, thank you for your feature suggestion! 

@rossdotparker and I have discussed the idea and it looks like this change would end up being considerably larger than one would think: uploading multiple files, normalizing them, displaying them, etc. There would be substantial knockons, including into the Markbook, which can display such submissions. I don’t think it is something we would look at changing in the core, particularly because our development efforts are primarily focused on refactoring.

Two solutions to perhaps suggest to the user: students zipping work into a single file and students using an online folder (in Dropbox, Google Drive, etc) and submitting a link.

Hope this helps!
