### ISSUE TITLE
Mysql password cannot contain "/" (V 19.0.00)

### ISSUE THREAD

**Issue by kaitsh** [GibbonEdu/core#1040]
**Describe the bug**
We get an error invalid input error in the initial install section (`/installer/install.php?step=1`) if the database password contains a "/".

**To Reproduce**
1. Create a database user with a password that contains a slash.
2. Go to the Gibbon URL and start the installer
3. Input the database config
4. On submit we get a redirect to `/install.php?step=2` with the error message that the input is invalid.

**Expected behavior**
The site should handle all character for password (probably need to escape the string).

**Screenshots**
![image](https://user-images.githubusercontent.com/8351869/81705967-a3c90e80-943d-11ea-9231-d8cc3101c90e.png)

![image](https://user-images.githubusercontent.com/8351869/81705867-7c724180-943d-11ea-80fa-005db6fc765b.png)

**Your System**
 - Gibbon v19.0.00
 - Browser Firefox 76.0 (64-bit)

**Comment by jimbo8098** [comment]
Gibbon v19.0.00 is pretty old now, we're working on releasing v21.0.00 currently. This could be something that's been resolved in v20.0.00 so it may be worth checking that to see if you experience the same issue there.

**Comment by yookoala** [comment]
I believe the source of this problem is [here](https://github.com/GibbonEdu/core/blob/358c7b8f84826608b224638cd6e8f9e6c5b0da65/installer/install.php#L123-L128), where the installer checks if the database variables contains either `'`, `"`, `/` or `\`. If any variables contain any invalid characters, the flag `$isConfigValid` is set to `false` and [this error](https://github.com/GibbonEdu/core/blob/358c7b8f84826608b224638cd6e8f9e6c5b0da65/installer/install.php#L151-L154) will appear.

The situation has not changed even in the latest v21.0.00 commit 358c7b8.

One reason for the check, I guess, is to prevent code injection into the config file generated from [a twig template file](https://github.com/GibbonEdu/core/blob/358c7b8f84826608b224638cd6e8f9e6c5b0da65/resources/templates/installer/config.twig.html), where neither of the variables are properly escaped.

**Comment by SKuipers** [comment]
Thanks Jim and Koala for following up on this, and Koala for the fix! This issue has now been resolved in v21 👍
