### ISSUE TITLE
Reports Module Erases Comments

### ISSUE THREAD

**Issue by tr-j** [GibbonEdu/core#1377]
**Describe the bug**
During Proofreading comments are deleted unless the "Override" option is selected, which appears to disable some of the moderation functions.

**To Reproduce**

1. My user is an administrator both in the system itself and with the reports access.
2. Go to Assess / Reports / Proofread
3. Using the user dropdown select a different user
4. For each comment the radio button has options for "Looks Good!" or "Edit Comment"
5. If I "Edit Comment" then a new textarea will appear for editing.
6. Click Save.
7. The comment will appear as a diff showing the old comment and new comment with changes.
8. Click "Looks Good!"
9. Click Save

**Expected behavior**
The comment show be saved and marked Accepted or Done.

**Your System**

 - Multiple versions of Gibbon (including 22.00) appear to have the same issue.

**Additional context**
The POST does not include the comment because there is no textarea submitted when "Looks Done!" is selected. As well the state from the button is not different than other states from unedited comments which means that the comment cannot be retrieved from the database as is done with the "Accepted" state.
I looked for a way to change the CommentEditor to stay persistent as a textarea or preserve the comment as a hidden field, but I didn't see an easy way to do that and I wasn't sure what the intended behaviour was for this system.

**Comment by SKuipers** [comment]
Hi @tr-j, thanks for reporting this issue and sharing in-depth information. I've followed your steps to reproduce the issue but wasn't able to see the same behaviour you're reporting. We've just finished a reporting season using the proof reading tools with our school and haven't had any issues, so I wonder if there is something specific to your setup, either server side or locally. Here's an example screenshot, I can check Looks Good and submit several times in a row and the comment text doesn't disappear:

<img width="917" alt="Screenshot 2021-07-04 at 8 08 57 PM" src="https://user-images.githubusercontent.com/897700/124384506-21b43d00-dd04-11eb-9ee6-ab12a5e49153.png">

I wonder, similar to my previous response, if you can check your versions of PHP and MySQL, as well as browser extensions, and perhaps even test in another browser to rule that out.

**Comment by tr-j** [comment]
Hi,

I tested in PHP 7.3 and 8.0 and tested with Chrome and Firefox and continue to get the same issues. Another teacher has had the same thing happens and has disappearing comments as well. I expect it's something related to our config because it's a very visible and damaging error (losing all the comments). It appeared to me when I reviewed the code that this would happen consistently based on the variables in scope as I was testing, but I don't quite see what the problem is.

When I view the page and check the values of the variables on reporting_proofread.php they come back as:
`
$highestAction = 'Proof Read_all';
$proofReview = false;
`

Which puts me into this code block:
`  // PROOF READ MODE: view peer comments and optionally suggest edits
`
I would have expected to be in the $proofReview == true code block.
If I click on the Override checkbox I can't moderate changes, but I can simply edit them.

Without the Override checkbox I have this same error with disappearing comments.

Ultimately, the issue is that when $status == 'Done' (line 69 in reporting_proofreadProcess) doesn't save the comment.
`
84:                 'comment'  => $status == 'Edited' ? ($comments[$gibbonReportingValueID] ?? '') : '',
`
The comment value is trying to pull from the POST, but it has no value on 'Done', only on 'Edited'. However, I'm not sure that I was ever supposed to reach this point. We don't use collaborative proof reading and maybe that's distinctive to our school.

Thanks

**Comment by SKuipers** [comment]
Hi @tr-j My apologies this issue has been open so long. I've had another look, as we wrap up testing for the next version, and still cannot reproduce the error, even with the very helpful data you've provided. 

The way the proofs work is that they save the edited comments in a different table, and do not modify the original comment. The only time in the reporting_proofreadProcess.php script that the original comment is changed is when the user selects "Accept" or "Edit Comment" when there are pending changes. The line 84 you mention, where the comment is empty on the Done status, is for the proof data rather than the comment data, and this shouldn't overwrite or change the original comment.

I wish I could reproduce the exact issue you're seeing, as we certainly don't want any case where comments appear to go missing. However, even if they show up blank on the proof view for some reason, the original comment should still be intact in the database, in the report writing screen.

You've mentioned that you don't do collaborative proof reading. It looks like the workflow you're using is to use Edit Comment, then to use Looks Good on the same screen, by another use. This will reset the suggested changes, rather than directly editing the comment. The workflow is that another user can suggest edits, but only the original user can accept them. You don't want to change it back to Looks Good if there are pending edits. You would want the target user to accept the changes, or use the overrride to accept on their behalf. Hope this makes sense!

**Comment by SKuipers** [comment]
Wait, I just had a thought after hitting send... were you using the Proofread page to write the initial comments, rather than suggest edits? I think this could certainly cause the problems you're seeing! Comments should be written using the My Reporting & Write Reports pages, which stores them properly as original report values. The Proofread page should only be used to read and suggest edits to comments that teachers have already written. Perhaps this is the issue you're seeing, in which case switching to Looks Good would certainly clear the suggested edits.

**Comment by tr-j** [comment]
Hi Sandra,

Thank you for looking at this again. We are modifying our process this year
so that teachers submit comments, then a group of teachers will proofread
the comments, and then the school leadership does the final checks. I'm
hoping this aligns better with the way the software is intended to work and
we don't run into this issue anymore.

Thanks,

Tr. James
