### ISSUE TITLE
Unicode rendering in particular contexts

### ISSUE THREAD

**Issue by dowens76** [GibbonEdu/core#157]
I noticed the given names of our teachers are shortened to a first initial in certain contexts, such as in a list of staff. That is fine, but when this happens I have noticed that the "Đ" character displays as "�". I would have guessed this is just a font issue, but when the name appears in full, there is no such problem.

To reproduce, give a staff member the name Adams, Đức. The name should display correctly in the user profile and in Staff > View Staff Profiles. However, if you go to Timetable > View Timetable by Person, the � character displays for the first initial. 

This affects both v12 and v13 (installed as of two days ago).

**Comment by rossdotparker** [comment]
Daniel,

Thanks for reporting this bug. The characters in question are multibyte characters, but we were using the unibyte character version of substr (the standard PHP way to shorten a string). I have changed the function that formats names so that it now uses mb_substr instead. This should fix this case across the system, as far as names are concerned.

Please let us know if you notice the issue elsewhere. I am loath to do a mass find-and-replace on the whole code base, just in case it upsets something else. You can see the commit to the v13 dev branch at:

https://github.com/GibbonEdu/core/commit/7baa57777d17996bc6827f3201fa286696297a89

In your v13 install you can simply upload the new code, and run the Update function under Admin > System Admin, and keep working. The joys of running the unstable, cutting edge version!

Ross

**Comment by dowens76** [comment]
That fixed it. Thanks, Ross.
