### ISSUE TITLE
A Stored Cross-Site Scripting (XSS) injection vulnerability exists in Gibbon CMS version v22.0.01

### ISSUE THREAD

**Issue by truonghuuphuc** [GibbonEdu/core#1594]
[ Content removed by admin to follow proper security disclosure measures ]

**Comment by SKuipers** [comment]
Hi Trương Hữu Phúc. We greatly appreciate that you sent an email to our support team with this information. When it comes to security vulnerabilities, it is always best to share them directly via email rather than posting them publicly, as this gives our team the chance to patch it and safely update users systems. We greatly appreciate that you spotted this issue, please do see the response we already sent by email. 

To follow proper disclosure measures, I've removed the security information from your message. Thank you again for your help to share this information with us.

**Comment by truonghuuphuc** [comment]
I hope team patch vulnerabilities.
According to the team, is this vulnerability considered a cve?
Have a nice day team

Vào Th 2, 3 thg 1, 2022 vào lúc 11:11 Sandra Kuipers <
***@***.***> đã viết:

**Comment by truonghuuphuc** [comment]
Once the vulnerability has been patched,  I hope you response.Because i would like to report this to CVE Mitre for registering it with a CVE ID.
