### ISSUE TITLE
uploading zip photos not working on windows

### ISSUE THREAD

**Issue by gsukrawan** [GibbonEdu/core#161]
Hi Gibbon Dev, 

For windows computer when we are uploading zip file, it recognized as "application/x-zip-compressed", it is fine on Mac and Linux.

I open the code /var/www/gibbon/modules/User Admin/import_userPhotos.php

line 110 : if ($_FILES['file']['type'] != 'application/zip') {

I add this to make it worked on windows

line 110 : if (($_FILES['file']['type'] != 'application/zip') and ($_FILES['file']['type'] != 'application/x-zip-compressed')) {

**Comment by rossdotparker** [comment]
Hello gsukrawan,

Thanks for letting us know about this, and providing the solution. I believe you are on v12 (latest stable), and looking at the code base for v13 (due for release 20/01/2017), this issue has already been fixed in exactly the manner you suggest.

Can you confirm that you are using v12? Care to do a test of v13's script just to make sure?

Thanks,

Ross

**Comment by gsukrawan** [comment]
Thanks for your reply Ross, 
Yes, we are using v12.0.00 (latest stable)
If v13 is out and it stable, we will test it.
Thanks for your support Ross

**Comment by rossdotparker** [comment]
No problem. v13 is stable, fully tested, but not yet released. Please do not update the whole install, but if possible download the new version of the relevant script, and test it briefly within your v12 install (it should be fully backwards compatible): https://github.com/GibbonEdu/core/blob/v13.0.00/modules/User%20Admin/import_userPhotos.php

Ross
