### ISSUE TITLE
Tie Days to Dates select all check box is over-zealous

### ISSUE THREAD

**Issue by dowens76** [GibbonEdu/core#164]
Our school has a different timetable for each term. In the "Tie Days to Dates" action, there is a handy check box to select all for each day of the week. However, this check box is a bit over-zealous in that it selects all, regardless of term. If I select it for Term 1, it also selects for Term 2. If I select it for Term 2, it also selects for Term 1. This means I have to check each individual day for the entire term. This is time-consuming, but given that the check box is shown under the term, I think this is a bug.

**Comment by rossdotparker** [comment]
Daniel, well spotted. I think it was only ever supposed to select the whole year, and I never clocked the repeated checkboxes in the headers. However, it works much better as per your suggestion, selecting a term at a time. This has now been fixed in the v14 branch in the following commit:
and should be backwards compatible with

**Comment by dowens76** [comment]
Nice, thanks. I can confirm it works on v13.

**Comment by rossdotparker** [comment]
My pleasure, and thanks for the confirmation. Apologies that it took a few days to get there!
