### ISSUE TITLE
Bug: Language does not change on a fresh intstall (v26)

### ISSUE THREAD

**Issue by dom-madrid** [GibbonEdu/core#1814]
### Describe the Bug

I reinstalled v26 on a fresh VM with english as the install language.
Went on downloading and installing  spainsh and french language packs.
Tried to change my user language to either language to no effect (logout and login) no changes.
Tried to change the entire system language to no effect either.
It's a fresh install. I had no time to fool around in the VM to break something. Am I missing something ?

### To Reproduce

1 Create new VM
2. install Gibbonedu 26
3. download new language
4. activate language (for user or system)
5. get the UI in the right language

### Expected behavior

get th UI in the right language (french or spaning in my case)

### Actual behavior

Ui still in english

### Screenshots

![Screenshot from 2024-03-28 16-02-53](https://github.com/GibbonEdu/core/assets/5640062/a864b3ca-1470-43aa-bcf5-8779aa0b15e5)
![Screenshot from 2024-03-28 16-03-46](https://github.com/GibbonEdu/core/assets/5640062/4b698a85-cf21-4c66-a162-995edc103438)

### Gibbon version

26.00

### Browser

Other (specify below)

### Browser Version

Opera Version:108.0.5067.40

**Comment by SKuipers** [comment]
Thanks @yookoala, I suspect this is the case too.

Hi @dom-madrid, thanks for your bug report. In this case, it sounds like since you're using a new VM, the server itself does not have the locales installed. Here is a link to the documentation to help get you started: https://docs.gibbonedu.org/administrators/misc/internationalisation/
