### ISSUE TITLE
Responsive/Mobile support ?

### ISSUE THREAD

**Issue by kaustubhkabra** [GibbonEdu/core#208]
Is this project responsive or has supports for native iOS/Android apps ?

**Comment by SKuipers** [comment]
Hi @kk-code 

Gibbon is not currently responsive, but we're working to add responsive design in future versions. 

Here's some more info from Ross (re-posting from the Gibbon forum thread https://ask.gibbonedu.org/discussion/comment/2640/#Comment_2640):

> We feel a real need to make Gibbon mobile responsive, and this is something we have played with in the past. Where we have always gotten stuck is that the code base is so big with so much repeated code. So, v14 is focused on making the code based object oriented in order to reduce code repetition. Once this is done, it will be much easier, hopefully in v15 (all going to plan) to get responsive design in place. We are working hard to make this happen, but as always, we are just volunteers and so not making any promises. Ross.

**Comment by SKuipers** [comment]
Hi kaustubhkabra,

I've added this issue to the Responsive Design milestone. Over the last couple versions we've pushed ahead with a lot of the refactoring work on the Gibbon core, including a nearly complete re-write of the html forms, and are optimistically aiming to start introducing responsive elements in v17.

Thanks!

**Comment by crayner** [comment]
At the moment it an API written in Symfony 4.x with a REACT front-end.  I have started by targeting a couple of tasks that are used in a classroom, so at the moment a simple display of the calendar for today, attendance management for teachers,  Display Notifications and Messages, but not likes. 

Plans, should this get traction, would be to move towards students seeing both calendar and due tasks, teachers being able to add marks, plus move towards a full Apple/Android APP if possible.  

Screenshots from my mobile attached. Attendance saves on every change, attendance buttons change colour (orange/green) if attendance has been taken.  Calendar ONLY shows events, not empty space.
Google is integrated.
![screenshot_20190121-134650](https://user-images.githubusercontent.com/918953/51450149-94730d00-1d83-11e9-9ef3-8c1ccd579cbd.png)
![screenshot_20190121-134727](https://user-images.githubusercontent.com/918953/51450151-94730d00-1d83-11e9-8b6b-f9798b47cb87.png)

**Comment by kaustubhkabra** [comment]
Hi everyone on the thread, this would be super helpful! Excited to see this being taken up.

**Comment by SKuipers** [comment]
Hi all! The Gibbon core team have been hard at work refactoring the codebase the past several versions to prep it for responsive themes. The world is full of a variety of opinions, approaches and ideas on how to tackle a problem: one person's "near impossible" is another person's idea of a worthy challenge 😃

**Comment by danfelbm** [comment]
> Hi all! The Gibbon core team have been hard at work refactoring the codebase the past several versions to prep it for responsive themes. The world is full of a variety of opinions, approaches and ideas on how to tackle a problem: one person's "near impossible" is another person's idea of a worthy challenge 😃

Yes! I just saw that... The whole new 'templates' folder inside resources, right? I don't think that was there before

> Hi @kaustubhkabra ,
> At the moment it an API written in Symfony 4.x with a REACT front-end, so a browser on your phone, not an APP. I have started by targeting a couple of tasks that are used in a classroom, so at the moment a simple display of the calendar for today, attendance management for teachers, Display Notifications and Messages, but not likes.

That looks amazing... Great work!

**Comment by crayner** [comment]
Announcing the pre-release of a Mobile version for Gibbon.  http://gibhelp.craigrayner.com  This only does Attendance at the moment, but I am sure that development suggestions will soon follow.

**Comment by SKuipers** [comment]
Hi everyone! I’m excited to announce Gibbon v18, releasing June 20th, will be fully mobile responsive 📱🎉 This will be a milestone release for us, building on the past several versions of refactoring work in the Gibbon core.

When we started down the road to refactoring, our aim was to incrementally update the entire codebase, rather than focusing on one or two mobile features. This decision was made with the future of the core in mind: to help make it more usable by module and theme developers alike. 

It has been a long road, but this dedication to sustainability has helped us make some huge steps towards modernizing the code. The most recent of these steps has been to add in responsive templates, so I’m happy to get to hit the close button on this issue and declare this question answered 😎 Thanks for your continued interest in our project! Looking forward to the v18 release.

_Some mobile previews from the development branch:_
![IMG_3763](https://user-images.githubusercontent.com/897700/55782626-4dbdc500-5adf-11e9-97c8-e13a767e6ea0.PNG)
![IMG_3764](https://user-images.githubusercontent.com/897700/55782628-4f878880-5adf-11e9-8a55-0c6d8b72634d.PNG)

**Comment by rossdotparker** [comment]
Sandra, it's a thing of beauty! I've not been as excited about a release of Gibbon since v8.0.00 (Linguist). I'm practically brachiating! Thanks for all of your hard work : )
