### ISSUE TITLE
User sync fails with truncated usernames

### ISSUE THREAD

**Issue by vktec** [GibbonEdu/core#637]
## Expected Behavior
When importing a CSV with sync mode, all existing users, including those whose usernames have been truncated to fit the database fields, should be updated.

## Actual Behavior
Any users in the CSV whose existing usernames have been truncated to fit the field length cause an error. I suspect this is because Gibbon compares the usernames, does not find a match, and proceeds to `INSERT`. MySQL then truncates the username and finds a conflict, causing the error.

## Steps to Reproduce
1. Create a user CSV with usernames larger than the username field length
2. Import this CSV normally to populate the database
3. Import this same CSV with sync mode

## Your Environment
* Gibbon Version: 16.0.01

**Comment by SKuipers** [comment]
Hi vktec,

Thanks for bringing this to our attention! Taking a look at the script, it does appear that the behaviour you're seeing is unintentional. One way to fix it (without changing any code) may be to use a spreadsheet tool to edit & truncate the usernames yourself before import.

I think for a long-term fix, rather than re-writing that script, our plan is to start phasing out those import scripts in favor of the Data Admin imports, which should soon be part of the core (in v17.0.00). Be sure to check out this module if you're planning to import lots of data, as it has more tools to handle validating and importing data.

Thanks!
